// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUlNuO8BlCpMZkuANw5Zy2JZPAG2wtcsI',
    appId: '1:656187236705:web:02fc458df37ecfcd10a520',
    messagingSenderId: '656187236705',
    projectId: 'cs-310-phase3-dbdd0',
    authDomain: 'cs-310-phase3-dbdd0.firebaseapp.com',
    storageBucket: 'cs-310-phase3-dbdd0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwrZuuwghgDkrmJTf58dypfmFkPXYsqyI',
    appId: '1:656187236705:android:cb85797332cb024710a520',
    messagingSenderId: '656187236705',
    projectId: 'cs-310-phase3-dbdd0',
    storageBucket: 'cs-310-phase3-dbdd0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADL6Ca3cDvXOLMHLuuMAA19m2GqW6Cka4',
    appId: '1:656187236705:ios:df79a377a1bf5d6f10a520',
    messagingSenderId: '656187236705',
    projectId: 'cs-310-phase3-dbdd0',
    storageBucket: 'cs-310-phase3-dbdd0.firebasestorage.app',
    iosBundleId: 'com.example.loginUi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADL6Ca3cDvXOLMHLuuMAA19m2GqW6Cka4',
    appId: '1:656187236705:ios:df79a377a1bf5d6f10a520',
    messagingSenderId: '656187236705',
    projectId: 'cs-310-phase3-dbdd0',
    storageBucket: 'cs-310-phase3-dbdd0.firebasestorage.app',
    iosBundleId: 'com.example.loginUi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUlNuO8BlCpMZkuANw5Zy2JZPAG2wtcsI',
    appId: '1:656187236705:web:398d0b805eaa565d10a520',
    messagingSenderId: '656187236705',
    projectId: 'cs-310-phase3-dbdd0',
    authDomain: 'cs-310-phase3-dbdd0.firebaseapp.com',
    storageBucket: 'cs-310-phase3-dbdd0.firebasestorage.app',
  );
}
